vim.keymap.set("n", "<Tab>", "<cmd>BufferLineCycleNext<CR>", { desc = "Next buffer", silent = true })
vim.keymap.set("n", "<S-Tab>", "<cmd>BufferLineCyclePrev<CR>", { desc = "Prev buffer", silent = true })
-- vim.keymap.set("n", "%", "ggVG", { desc = "Select all" })
vim.keymap.set("n", "Y", "Vy", { desc = "Yank Line" })
vim.keymap.set("n", "gs", "^", { desc = "Go to first word" })
vim.keymap.set("n", "gl", "$", { desc = "Go to last word" })
vim.keymap.set("n", "U", "<C-r>", { desc = "redo" })
vim.keymap.set("n", "<enter>", "o", { desc = "line break" })
vim.keymap.set("n", "<BS>", "X", { desc = "Back Space" })
vim.keymap.set("n", "<Del>", "x", { desc = "Delete" })
-- Claude Codeに渡すために現在開いているファイル名と行番号をクリップボードにコピーする
vim.keymap.set("n", "ga", function()
  local path = vim.fn.expand("%:p")
  local line = vim.fn.line(".")
  vim.fn.setreg("+", "@" .. path .. ":" .. line .. " ")
  print("Copied @" .. path .. " #" .. line)
  print("")
end, { desc = "Copy filename:line to clipboard" })

-- rename
vim.keymap.set("n", "<leader>rn", ":IncRename")

vim.keymap.set("n", "<leader>F", function()
  vim.diagnostic.open_float(nil, { focus = false })
end, { desc = "Go to error float" })
