[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[[language]]
name = "html"
indent = { tab-width = 4,unit="    " }
language-servers = ["vscode-html-language-server","tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "html"] }
auto-format = true

[[language]]
name = "css"
indent = { tab-width = 4,unit="    " }
language-servers = ["tailwindcss-ls","vscode-css-language-server",]
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "typescript"
indent = { tab-width = 4,unit="    " }
language-servers = ["typescript-language-server"]
formatter = { command = "prettier", args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
indent = { tab-width = 4,unit="    " }
language-servers = ["typescript-language-server","tailwindcss-ls","emmet-ls"]
formatter = { command = "prettier", args = ["--parser", "babel-ts"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman"]

[language-server.emmet-ls]
command = "emmet-language-server"
args = ["--stdio"]
